### ISSUE TITLE
Disable animation

### ISSUE THREAD

**Issue by stact** [mgcrea/angular-motion#19]
Hi,

Do we have a way to disable animation on xs view? Or on a particular element?

Thank you for your feedback :)

**Comment by stact** [comment]
I get it.
I can specify a "no-animation" class for example, where "no-animation"  does not exist :)

``` html
<a href="#" class="dropdown-toggle" data-animation="no-animation" bs-dropdown="links">
   My dropdown
</a>
```
Hope this will help someone

**Comment by mgcrea** [comment]
You could also override defaults globally:

```
angular.module('myApp')
.config(function($dropdownProvider) {
  angular.extend($dropdownProvider.defaults, {
    animation: false
  });
})
```
